/* SPDX-License-Identifier: CC-BY-4.0 */
package net.claustra01.clayium.machine;

import java.util.List;

/** Chemical materials introduced by the original progression through Precision tier. */
public final class MaterialCatalog {
    public record Entry(String id, String displayName, String originalTexture) {}

    public static final List<Entry> ENTRIES = List.of(
            item("salt_dust", "Salt Dust", "saltdust"),
            item("calcium_chloride_dust", "Calcium Chloride Dust", "calciumchloridedust"),
            item("sodium_carbonate_dust", "Sodium Carbonate Dust", "sodiumcarbonatedust"),
            item("quartz_dust", "Quartz Dust", "quartzdust"),
            item("impure_silicon_ingot", "Impure Silicon Ingot", "impuresiliconingot"),
            item("impure_silicon_dust", "Impure Silicon Dust", "dust_base"),
            item("impure_silicon_large_plate", "Large Impure Silicon Plate", "largeplate_base"),
            item("silicone_dust", "Silicone Dust", "dust_base"),
            item("silicone_ingot", "Silicone Ingot", "ingot_base"),
            item("silicone_plate", "Silicone Plate", "plate_base"),
            item("silicone_large_plate", "Large Silicone Plate", "largeplate_base"),
            item("impure_aluminium_ingot", "Impure Aluminium Ingot", "ingot_base"),
            item("impure_aluminium_plate", "Impure Aluminium Plate", "plate_base"),
            item("impure_aluminium_large_plate", "Large Impure Aluminium Plate", "largeplate_base"),
            item("silicon_dust", "Silicon Dust", "dust_base"),
            item("silicon_ingot", "Silicon Ingot", "ingot_base"),
            item("silicon_large_plate", "Large Silicon Plate", "largeplate_base"),
            item("impure_aluminium_dust", "Impure Aluminium Dust", "dust_base"),
            item("aluminium_dust", "Aluminium Dust", "dust_base"),
            item("aluminium_ingot", "Aluminium Ingot", "ingot_base"),
            item("aluminium_plate", "Aluminium Plate", "plate_base"),
            item("aluminium_large_plate", "Large Aluminium Plate", "largeplate_base"),
            item("impure_magnesium_dust", "Impure Magnesium Dust", "dust_base"),
            item("magnesium_dust", "Magnesium Dust", "dust_base"),
            item("magnesium_ingot", "Magnesium Ingot", "ingot_base"),
            item("impure_sodium_dust", "Impure Sodium Dust", "dust_base"),
            item("sodium_dust", "Sodium Dust", "dust_base"),
            item("sodium_ingot", "Sodium Ingot", "ingot_base"),
            item("impure_lithium_dust", "Impure Lithium Dust", "dust_base"),
            item("lithium_dust", "Lithium Dust", "dust_base"),
            item("lithium_ingot", "Lithium Ingot", "ingot_base"),
            item("impure_zirconium_dust", "Impure Zirconium Dust", "dust_base"),
            item("zirconium_dust", "Zirconium Dust", "dust_base"),
            item("zirconium_ingot", "Zirconium Ingot", "ingot_base"),
            item("impure_zinc_dust", "Impure Zinc Dust", "dust_base"),
            item("impure_manganese_dust", "Impure Manganese Dust", "dust_base"),
            item("impure_calcium_dust", "Impure Calcium Dust", "dust_base"),
            item("impure_potassium_dust", "Impure Potassium Dust", "dust_base"),
            item("impure_nickel_dust", "Impure Nickel Dust", "dust_base"),
            item("impure_iron_dust", "Impure Iron Dust", "dust_base"),
            item("impure_beryllium_dust", "Impure Beryllium Dust", "dust_base"),
            item("impure_lead_dust", "Impure Lead Dust", "dust_base"),
            item("impure_hafnium_dust", "Impure Hafnium Dust", "dust_base"),
            item("impure_chrome_dust", "Impure Chrome Dust", "dust_base"),
            item("impure_titanium_dust", "Impure Titanium Dust", "dust_base"),
            item("impure_strontium_dust", "Impure Strontium Dust", "dust_base"),
            item("impure_barium_dust", "Impure Barium Dust", "dust_base"),
            item("impure_copper_dust", "Impure Copper Dust", "dust_base"),
            item("manganese_dust", "Manganese Dust", "dust_base"),
            item("manganese_ingot", "Manganese Ingot", "ingot_base"),
            item("calcium_dust", "Calcium Dust", "dust_base"),
            item("calcium_ingot", "Calcium Ingot", "ingot_base"),
            item("potassium_dust", "Potassium Dust", "dust_base"),
            item("potassium_ingot", "Potassium Ingot", "ingot_base"),
            item("hafnium_dust", "Hafnium Dust", "dust_base"),
            item("hafnium_ingot", "Hafnium Ingot", "ingot_base"),
            item("strontium_dust", "Strontium Dust", "dust_base"),
            item("strontium_ingot", "Strontium Ingot", "ingot_base"),
            item("barium_dust", "Barium Dust", "dust_base"),
            item("barium_ingot", "Barium Ingot", "ingot_base"),
            item("beryllium_dust", "Beryllium Dust", "dust_base"),
            item("beryllium_ingot", "Beryllium Ingot", "ingot_base"),
            item("iron_dust", "Iron Dust", "dust_base"),
            item("steel_dust", "Steel Dust", "dust_base"),
            item("steel_ingot", "Steel Ingot", "ingot_base"),
            item("clay_steel_dust", "Clay Steel Dust", "dust_base"),
            item("clay_steel_ingot", "Clay Steel Ingot", "ingot_base"),
            item("clay_steel_plate", "Clay Steel Plate", "plate_base"),
            item("clay_steel_large_plate", "Large Clay Steel Plate", "largeplate_base"),
            item("zinc_dust", "Zinc Dust", "dust_base"),
            item("zinc_ingot", "Zinc Ingot", "ingot_base"),
            item("zincalminium_dust", "Zincalminium Dust", "dust_base"),
            item("zincalminium_ingot", "Zincalminium Ingot", "ingot_base"),
            item("zinconium_dust", "Zinconium Dust", "dust_base"),
            item("zinconium_ingot", "Zinconium Ingot", "ingot_base"),
            item("az91d_dust", "AZ91D Dust", "dust_base"),
            item("az91d_ingot", "AZ91D Ingot", "ingot_base"),
            item("az91d_plate", "AZ91D Plate", "plate_base"),
            item("az91d_large_plate", "Large AZ91D Plate", "largeplate_base"),
            item("zk60a_dust", "ZK60A Dust", "dust_base"),
            item("zk60a_ingot", "ZK60A Ingot", "ingot_base"),
            item("zk60a_plate", "ZK60A Plate", "plate_base"),
            item("zk60a_large_plate", "Large ZK60A Plate", "largeplate_base"),
            item("manipulator", "Manipulator", "manipulator"),
            item("rubidium_ingot", "Rubidium Ingot", "ingot_base"),
            item("caesium_ingot", "Caesium Ingot", "ingot_base"),
            item("francium_ingot", "Francium Ingot", "ingot_base"),
            item("radium_ingot", "Radium Ingot", "ingot_base"),
            item("actinium_ingot", "Actinium Ingot", "ingot_base"),
            item("thorium_ingot", "Thorium Ingot", "ingot_base"),
            item("protactinium_ingot", "Protactinium Ingot", "ingot_base"),
            item("uranium_ingot", "Uranium Ingot", "ingot_base"),
            item("neptunium_ingot", "Neptunium Ingot", "ingot_base"),
            item("lanthanum_ingot", "Lanthanum Ingot", "ingot_base"),
            item("cerium_ingot", "Cerium Ingot", "ingot_base"),
            item("praseodymium_ingot", "Praseodymium Ingot", "ingot_base"),
            item("neodymium_ingot", "Neodymium Ingot", "ingot_base"),
            item("titanium_ingot", "Titanium Ingot", "ingot_base"),
            item("vanadium_ingot", "Vanadium Ingot", "ingot_base"),
            item("cobalt_ingot", "Cobalt Ingot", "ingot_base"),
            item("nickel_ingot", "Nickel Ingot", "ingot_base"),
            item("palladium_ingot", "Palladium Ingot", "ingot_base"),
            item("copper_ingot", "Copper Ingot", "ingot_base"),
            item("silver_ingot", "Silver Ingot", "ingot_base"),
            item("gold_ingot", "Gold Ingot", "ingot_base"),
            item("tantalum_ingot", "Tantalum Ingot", "ingot_base"),
            item("tungsten_ingot", "Tungsten Ingot", "ingot_base"),
            item("lead_ingot", "Lead Ingot", "ingot_base"),
            item("tin_ingot", "Tin Ingot", "ingot_base"),
            item("antimony_ingot", "Antimony Ingot", "ingot_base"),
            item("bismuth_ingot", "Bismuth Ingot", "ingot_base"),
            item("phosphorus_dust", "Phosphorus Dust", "dust_base"),
            item("sulfur_dust", "Sulfur Dust", "dust_base"));

    private MaterialCatalog() {}

    private static Entry item(String id, String name, String texture) {
        return new Entry(id, name, texture);
    }
}
